# Generated by Django 4.2.4 on 2024-01-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=40)),
                ('key_words', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
